name: Daily Update
on:
  push:
  schedule:
    - cron: "0 0 * * *"
env:
  USERNAME: "artifabrian"
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Get source
        uses: actions/checkout@v3
      - name: Get Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: "pip"
      - name: Install dependencies
        run: python -m pip install pipenv
      - name: Install dependencies 2
        run: |
          pipenv instal
      - name: Update README.md
        run: pipenv run scrapper.py --username ${{ env.USERNAME }} > README.md
      - name: Commit changes
        uses: artifabrian/git-auto-commit-action@v4
        with:
          commit_message: Update README.md
          file_pattern: README.md