name: Daily Update

on:
  push:
    branches: [ master, develop ]
  schedule:
    - cron: "0 0 * * 1-5"
env:
  USERNAME: "artifabrian"
jobs:
  update:
    runs-on: ubuntu-latest

    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write

    steps:
      - name: Get source
        uses: actions/checkout@v3
      - name: Get Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: "pipenv"
      - name: Install dependencies
        run: python -m pip install pipenv
      - name: Install dependencies 2
        run: |
          pipenv install
      - name: Update README.md
        run: pipenv run python scrapper.py --username ${{ env.USERNAME }} > README.md
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update README.md
          file_pattern: README.md